
- id: doi:10.1038/s41591-020-1008-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41591-020-1008-z/MediaObjects/41591_2020_1008_Fig1_HTML.png?as=webp

- id: doi:10.1056/EVIDoa2200008
  image: https://evidence.nejm.org/cms/10.1056/EVIDoa2200008/asset/6e698239-222b-49ea-baaa-e64268197dfa/assets/images/large/evidoa2200008_f2.jpg
  buttons:
    - type: source
      text: R Package
      link: https://github.com/papaemmelab/ipssm
    - type: website
      text: Calculator
      link: http://www.mds-risk-model.com
  tags:
    - MDS
    - Cancer
    - Hematology
  repo: papaemmelab/ipssm

- id: doi:10.1038/s41467-022-32103-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-32103-8/MediaObjects/41467_2022_32103_Fig3_HTML.png?as=webp
